
language: python
matrix:
  include:
   - python: "3.5"
   - python: "nightly"
  allow_failures:
    # Doesn't currently work with pyinstaller
   - python: "nightly"

before_install:
 - "pip install pyinstaller"

install:
 - "./install.sh --noroot"

script:
 - "./integration_tests.sh"
 - "./build.sh"
