
language: python
python:
# - "3.3"
# - "3.4"
 - "3.5"
 - "nightly" # currently points to 3.6-dev

install:
 - "./install.sh --noroot"

script:
 - "python3 -c 'import aw.core'"
 - "python3 -c 'import aw.client'"
 - "python3 -c 'import aw.server'"
